### ISSUE TITLE
OMV TS3 plugin start by root. its not secure.

### ISSUE THREAD

**Issue by touhoku-japan** [OpenMediaVault-Plugin-Developers/openmediavault-teamspeak3#1]
I think OMV TS3 plugin is not secure. because its just run by "root". please change TS3 of exclusive use "user". e.g. add user "ts3-server" , "teamspeak3"

**Comment by ryecoaaron** [comment]
If you look in the /usr/share/openmediavault/module/teamspeak3.inc file, the service is started and run by the ts3 user.  Normally, the user would be specified in the init file but it is not with this plugin.
